language: node_js

node_js:
  - '0.10'
  - '0.11'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm install
  - bower install
  - gulp test

deploy:
  provider: heroku
  skip_cleanup: true
  all_branches: true
  strategy: api
  api_key:
    secure: WW8C1izUPCDV+6JDIzMfZEj2Cgqspt9063wxP9Y+FC6HKXAAKI5HBzCpQUzKtsgpmq55bv7++2P2QQxw0aqHaypPlDHlhzulVDjYeXmn/3fuh8ZT8ViAcSSjFiMoT4qsOB1Zc575FhV2yHVP3VwhLq/O0Y/zlFT53bOnDGiKmZk=
  app: pellucid
  on:
    repo: Wildhoney/Pellucid

env:
  global:
    - secure: P36W/MYFAcjkpT6LGjwJbzYynlc2ROgl4FUt/VYo8OijXWy4Ar3/YgDA/0Etp0Nl6Q05HAkIZyRbVZdGj+XYalf38wPSLkmIHgfFu8YzmunDkMhBtmsDsdNE4JPawW+NMVgyBWFMYPkYiyUQ+gCF6nmibqKQTDyi04+CpJWFVkk=
    - secure: hlvQm1mKita0lk+f8nse1mXEIfaJWR/uLhySRYYfA9gfUmqIOwaRIzobzaOUDcxU+QPLPGQIxo8+xc2cEr1RSHPs3jEDgPDj3aBbSCIu1AKd64lokMdUscVKLlHnR7LIQDULm7BPacUZPRy6Q1OaCiAkdimYPstmVxttHLWhZ/o=
