language: node_js

node_js:
  - '0.10'
  - '0.11'

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm install
  - bower install
  - gulp test
  - gulp build

deploy:
  provider: heroku
  skip_cleanup: true
  all_branches: true
  strategy: api
  api_key:
    secure: WW8C1izUPCDV+6JDIzMfZEj2Cgqspt9063wxP9Y+FC6HKXAAKI5HBzCpQUzKtsgpmq55bv7++2P2QQxw0aqHaypPlDHlhzulVDjYeXmn/3fuh8ZT8ViAcSSjFiMoT4qsOB1Zc575FhV2yHVP3VwhLq/O0Y/zlFT53bOnDGiKmZk=
  app: pellucid
  on:
    repo: Wildhoney/Pellucid

env:
  global:
    - secure: DCr+UXJU/+leVkb05ZUhHa4+EoHReLCzFqA4zr78Rc1bujQ7UO1peNbobQSF/C7BMzhb8brdO57n9XBM28qto976fXI7Rn5jXWpkf6LtcoQa0dNNaLkiLGpAhsdvRkSQj8QXQzFNvX5Zwr61WPnZHlRFDkJSB6TbSXrzUKbZxIM=
    - secure: fW+KHnK4q4pd/Vtu3SaRLuqaWFTX31KsKl3UZ9sdlCRmL/YkMnFLbjT4UZsS/0F0YoILpKD4BZh6sTbv3HQqKnjM5bAY0odhOPemd0tSHkQJadB45rzX5riO24Y8efdeu6dX4eDwVUnKuBiOH0irQudJyvQaGhV3UI+/hGBquzA=
